app/app/Http/routes.php
<?php
use App\Http\Controllers\SiteController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ImagensController;


// rotas do site
Route::get('/', ['as'=>'index', 'uses'=>'SiteController@index']);
Route::post('/email', ['as'=>'email', 'uses'=>'SiteController@email']);

Route::get('/teste', ['as'=>'teste', 'uses'=>'SiteController@teste']);


//rotas de autenticação
Route::get('login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@showLogin']);
Route::post('login', ['as'=>'auth.login_ajax', 'uses'=>'Auth\AuthController@postLogin']);
Route::get('logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);


// rotas do painel admin
Route::group(['prefix' => 'admin', 'as'=>'admin.', 'middleware'=>'auth'], function () {
	Route::get('/logout', ['as'=>'auth.logout', 'uses'=>'Auth\AuthController@logout']);
	Route::get('/', ['as'=>'dashboard', 'uses'=>'AdminController@index']);

	Route::get('/dashboard', ['as'=>'dashboard', 'uses'=>'AdminController@index']);

	//rotas dos posts
	Route::group(['prefix' => 'posts', 'as'=>'posts.'], function () {
		//rotas do painel
		Route::get('/listar', ['as'=>'listar', 'uses'=>'AdminController@postsShow']);
		Route::get('/cadastrar', ['as'=>'cadastrar', 'uses'=>'AdminController@postsCreate']);
		Route::get('/editar/{id?}', ['as'=>'editar', 'uses'=>'AdminController@postsEdit']);

		//rotas da API
		Route::post('/', ['as'=>'salvar', 'uses'=>'PostsController@store']);
		Route::get('/', ['as' => 'listar_dt', 'uses'=>'PostsController@datatables_ajax']);
		Route::put('/editar/{id?}', ['as'=>'editar', 'uses'=>'PostsController@update']);
		Route::delete('/{id?}', ['as'=>'deletar', 'uses'=>'PostsController@destroy']);

		Route::put('/editar_ordenacao', ['as'=>'editar_ordenacao', 'uses'=>'PostsController@updateOrdenacao']);
	});

	Route::group(['prefix' => 'imagens', 'as'=>'imagens.'], function () {
		//rotas do painel
		Route::get('/', ['as'=>'listar', 'uses'=>'AdminController@imagensShow']);

		//rotas da API
		Route::post('/', ['as'=>'dz_action', 'uses'=>'ImagensController@DropzoneAction']);
		Route::put('/editar/{id?}', ['as'=>'editar', 'uses'=>'ImagensController@update']);
		Route::delete('/{id?}', ['as'=>'deletar', 'uses'=>'ImagensController@destroy']);

		Route::get('/html_lista', ['as'=>'html_lista', 'uses'=>'ImagensController@html_lista']);
	});
});

app/app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    public $timestamps = true;

	protected $guarded = array('id');
	protected $fillable = array('id_usuario', 'mostrar_pagina_inicial', 'slug', 'ordem', 'titulo', 'conteudo');

	public static $rules = array(
		'titulo' 				=> 'required|min: 5',
		'conteudo' 				=> 'required'
	);

}

app/app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Posts;
use Auth;
use DB;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Mail;
use App\Http\Controllers\Route;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Validator;
use Yajra\Datatables\Facades\Datatables;
use Cache;

class PostsController extends Controller
{

	public function __construct()
	{
		
	}

	public function datatables_ajax()
	{
		//return Datatables::of(Campeonatos::query())->make(true);
		return Datatables::queryBuilder(
					DB::table('posts')
					->select('*')
		)->make(true);
	}

	public function store(Request $request)
	{
		/*$input = $request->all();

		if ($request->imagem) {
			$imageName = $request->nome . "." . $request->imagem->getClientOriginalExtension();
			$request->file('imagem')->move(base_path() . '/public/site/img/post/', $imageName);

			$input['imagem'] = 'site/img/post/' . $imageName;
		}

		$id = Posts::create($input)->id;

		\Session::flash('message', 'Postagem criada com sucesso! ID:('.$id.')');
		return Redirect::route('posts.table');*/
		$input = $request->all();

		$validator = Validator::make($input, Posts::$rules);

		if ($validator->fails()) {
			$erros = $validator->errors()->all();
			
			return Response()->json([
				'code' => 400,
				'message' => $erros
			], 400);
		}

		$post = new Posts;

		//pego o usuario
		$user = Auth::user();
		$userid = $user->id;

		$input["id_usuario"] = $userid;

		$post = $post->create($input);

		Cache::flush();

		if($post->id) {
			return Response()->json([
				'id' => $post->id,
				'code' => 200,
				'message' => 'O cadastro foi realizado com sucesso.'
			], 200);
		} else {
			return Response()->json([
				'code' => 400,
				'message' => 'Houve um erro no cadastro.'
			], 400);
		}
	}

	public function update($id, Request $request)
	{
		$input = $request->all();

		$post = Posts::findOrFail($id);
		$post->update($input);

		Cache::flush();

		if($post->id) {
			return Response()->json([
				'id' => $post->id,
				'code' => 200,
				'message' => 'A edição foi realizada com sucesso.'
			], 200);
		} else {
			return Response()->json([
				'code' => 400,
				'message' => 'Houve um erro na edição.'
			], 400);
		}
	}

	public function updateOrdenacao(Request $request)
	{
		$ordenacao = $request->sortable;
		//$posts = Posts::get()->keyBy("id");

		$retorno = "";
		foreach($ordenacao as $posicao=>$id) {
			//$posts[$id]->ordem = $posicao+1;
			$retorno .= "ID: " .$id. " - Posic: " . ($posicao + 1) . "<br />";
			$post = Posts::findOrFail($id)->update(["ordem" => ($posicao + 1)]);
		}

		Cache::flush();

		return Response()->json([
			'code' => 200,
			'message' => 'A edição foi realizada com sucesso.'
		], 200);
	}

	public function destroy($id)
	{
		$post = Posts::findOrFail($id);

		$post->delete();

		Cache::flush();

		if($post->id) {
			return Response()->json([
				'id' => $post->id,
				'code' => 200,
				'message' => 'O registro foi deletado com sucesso.'
			], 200);
		} else {
			return Response()->json([
				'code' => 400,
				'message' => 'Houve um erro na exclusão.'
			], 400);
		}
	}
}

app/resources/views/admin/posts/cadastrar.blade.php
@extends("admin.layouts.default")

@section("titulo", "Cadastrar Novo Post")

@section("conteudo")
<div class="row">
	<div class="col-md-12">
		<form role="form" id="cadastrar-postagem" class="form-validation" novalidate="novalidate">
			{!! csrf_field() !!}
			@if(isset($post->id))
				<input type="hidden" name="id" value="{{ @$post->id }}">
			@endif
			<div class="panel panel-default no-bd">
				<div class="panel-header bg-dark">
					<h2 class="panel-title">
						@if(isset($post->id))
							<strong>Editar</strong> postagem <small>(ID: {{ @$post->id }})</small>
						@else
							<strong>Cadastrar</strong> nova postagem
						@endif
					</h2>
				</div>
				<div class="panel-body bg-white">
					<div class="row">
						<div class="col-sm-12">
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<label class="control-label">Titulo</label>
										<input type="text" name="titulo" class="form-control" value="{{ @$post->titulo }}" placeholder="Insira o titulo do post..." required="" aria-required="true">
									</div>

									<div class="form-group">
										<label class="control-label">Slug</label>
										<input type="text" name="slug" class="form-control" value="{{ @$post->slug }}">
									</div>
								</div>
								
								<div class="col-sm-12">
									<div class="form-group togglebutton togglebutton-material-blue">
										<label class="control-label" style="font-weight: 500">Mostar na Página Inicial</label>
										<label style="text-align: right; float: right">
											<input type="checkbox" value="1" @if(@$post->mostrar_pagina_inicial) checked="" @endif name="mostrar_pagina_inicial" class="md-checkbox">
										</label>
									</div>
								</div>
							</div>
						</div>

						<div class="col-sm-12">
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<label class="control-label">Conteúdo</label>
										<textarea name="conteudo" class="form-control" rows="10">{{ @$post->conteudo }}</textarea>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Cadastrar</button>
				</div>
			</div>
		</form>
	</div>
</div>
@endsection

@section("extra-js")
<script src="{!! asset('admin/plugins/tinymce/tinymce.min.js') !!}"></script>
<script src="{!! asset('admin/plugins/noty/jquery.noty.packaged.min.js') !!}"></script>
<script type="text/javascript">
	tinymce.init({
		selector: 'textarea',
        theme: 'modern',
        skin: 'lightgray',
        content_style: "body{font-family: 'Montserrat', sans-serif;-webkit-font-smoothing: subpixel-antialiased;}.section-title{color:#021533;text-transform:uppercase;font-size:22px;line-height:26px;font-weight:700;margin-top:0;border-bottom:1px solid #021533;padding-bottom:10px;margin-bottom:40px}.section-title2{font-weight:700;color:#08aeac;font-size:20px;line-height:24px;letter-spacing:-1px;padding-left:15px;padding-top:5px;padding-bottom:5px;border-left:4px solid #08aeac}.resume-item{padding:15px;border:4px double #ccc;margin-bottom:15px}.section-item-title-1,.section-item-title-2{font-weight:700;color:#333;padding-left:0;line-height:22px;margin:0 0 8px;letter-spacing:-1px}.section-item-title-1{font-size:18px}.section-item-title-2{border-bottom:1px dotted #021533;padding-bottom:5px;font-size:15px}.graduation-time,.job{line-height:15px;font-style:italic;color:#555;font-size:10px;margin-top:5px;border-bottom:1px solid #ccc;padding-bottom:5px}.graduation-description p{font-size:12px}",
        content_css: 'https://netdna.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css',
        height: 200,
        noneditable_noneditable_class: 'fa',
        extended_valid_elements: 'span[*]',
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen importcss',
            'insertdatetime media table contextmenu paste code fontawesome noneditable'
        ],
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | fontawesome',
        content_css: '//www.tinymce.com/css/codepen.min.css',
        setup: function (editor) {
            editor.on('change', function () {
                editor.save();
            });
        }
	});

	$("#cadastrar-postagem").validate({		
		submitHandler: function (form) {
			event.preventDefault();

			$('input:checkbox').not(':checked').each(function() {
				$("#cadastrar-postagem").append("<input type='hidden' name='" + this.name + "' value='0' />");
			});

			generateNoty("topRight", "info", "Efetuando Cadastro!", "Por favor, aguarde um instante!");
			$.ajax({
				@if(isset($post->id))
					url: "{{ route('admin.posts.editar', $post->id) }}",
					type: "put",
				@else
					url: "{{ route('admin.posts.salvar') }}",
					type: "post",
				@endif

				data: $(form).serialize(),
				headers: {
					"Accept-Language": "application/json; charset=utf-8",
				},

				success: function(result, status, xhr) {
					generateNoty("topRight", "success", "Cadastro/Edição Efetuado com Sucesso!", result.message);
				},

				error: function(xhr, status, error) {
					if(xhr.status == 400) {
						response = xhr.responseJSON.message;
						var conteudo = "";
						for(var i = 0; i < response.length; i++) {
							conteudo += "[" + i + "] - " + response[i] + "<br />";
						}
					}

					generateNoty("topRight", "danger", "Cadastro/Edição não Efetuado!", conteudo);
				}
			});
			return false; 
		}
	});
</script>
@endsection

app/resources/views/admin/posts/listar.blade.php
@extends("admin.layouts.default")

@section("titulo", "Cadastrar Novo Jogo")

@section("conteudo")
<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default no-bd">
			<div class="panel-header bg-dark">
				<h2 class="panel-title"><strong>Listagem</strong> das Postagens/Páginas</h2>
			</div>
			<div class="panel-body bg-white">
				<table id="posts" class="table table-striped teste">
					<thead>
						<tr>
							<th>ID</th>
							<th>Titulo</th>							
							<th>Opções</th>
							<th>Ações</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default no-bd">
			<div class="panel-header bg-dark">
				<h2 class="panel-title"><strong>Ordenação</strong></h2>
			</div>
			<div class="panel-body bg-white">
				<ul class="posts-sortable">
					@foreach($posts as $post)
						<li id="{{ $post->id }}" class="bg-yellow" style="padding:5px; margin: 10px 0 10px 0">
							<i class="fa fa-folder-o"></i> {{ $post->titulo }} <small>(ID: <b>{{ $post->id }}</b>)</small>
						</li>
					@endforeach					
				</ul><br/>
				<a href="#" class="btn btn-primary btn-block btn-salvar-tree"><i class="fa fa-pencil-square-o"></i> Mudar Ordenação</a>
			</div>
		</div>
	</div>
</div>

<div id="modal_deletar" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header bg-red">
				<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title"><i class="fa fa-trash"></i> <strong>Deletar</strong> Postagem?</h4>
			</div>
			<div class="modal-body" style="margin-top: 10px">
				<p>Tem certeza que deseja prosseguir? Não será possível restaurar essa postagem posteriormente!</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Descartar</button>
				<button type="button" class="btn btn-transparent btn-danger delete-user" data-dismiss="modal">Deletar</button>
				{!! csrf_field() !!}
				<input type="hidden" id="postagem-deletar">
			</div>
		</div>
	</div>
</div>
@endsection

@section("extra-css")
<link href="{!! asset('admin/plugins/datatables/datatables.min.css') !!}" rel="stylesheet">
<link href="{!! asset('admin/plugins/datatables/datatables.bootstrap.css') !!}" rel="stylesheet">
@endsection

@section("extra-js")
<script src="{!! asset('admin/plugins/datatables/jquery.datatables.min.js') !!}"></script>
<script src="{!! asset('admin/plugins/datatables/datatables.bootstrap.js') !!}"></script>
<script src="{!! asset('admin/plugins/html-sortable/html.sortable.min.js') !!}"></script>

<script type="text/javascript">
	var tabela = $("#posts").DataTable({
		processing: true,
		serverSide: true,
		ajax: "{!! route('admin.posts.listar_dt') !!}",
		columns: [
			{ data: 'id', name: 'id' },
			{ data: 'titulo', name: 'titulo' },
			{ data: 'user_name', name: 'user_name' }
		],
		columnDefs: [
			{
				render: function(data, type, row) {
					var content="";
					if(row.mostrar_pagina_inicial == true) {
						content += '<button type="button" class="btn btn-sm btn-blue" data-toggle="tooltip" data-placement="top"  data-original-title="Mostrando na Página Inicial"><i class="fa fa-paper-plane-o"></i></button> ';
					} else {
						content += '<button type="button" class="btn btn-sm btn-dark" data-toggle="tooltip" data-placement="top" data-original-title="Não Mostrando na Página Inicial"><i class="fa fa-paper-plane-o"></i></button> ';
					}
					return content;
				},
				targets: 2
			},
			{
				render: function(data, type, row) {
					return '<a href="#" id="' + row.id + '" class="btn btn-success btn-sm"><i class="fa fa-eye"></i> Mostrar no Site</a> <a href="{!! route('admin.posts.editar') !!}/' + row.id + '" id="' + row.id + '" class="btn btn-blue btn-sm"><i class="fa fa-pencil"></i> Editar</a> <a href="#" id="' + row.id + '" class="btn btn-danger btn-sm btn-m-deletar" data-toggle="modal" data-target="#modal_deletar"><i class="fa fa-minus-square-o"></i> Deletar</a>';
				},
				targets: 3
			}
		],
		language: {
			"url": "{!! asset('admin/plugins/datatables/Portuguese-Brasil.json') !!}"
		}
	});

	$(document).on("click", ".btn-m-deletar", function() {
		$("#postagem-deletar").val($(this).context.id);
	});

	$(".delete-user").on("click", function() {
		generateNoty("topRight", "info", "Deletando Registro!", "Por favor, aguarde um instante!");
		$.ajax({
			url: $("#postagem-deletar").val(),
			type: "delete",
			data: { 
				'id': $("#postagem-deletar").val(),
				'_token': $('input[name=_token]').val()
			},
			headers: {
				"Accept-Language": "application/json; charset=utf-8",
			},

			success: function(result, status, xhr) {
				generateNoty("topRight", "success", "Registro deletado com Sucesso!", result.message);
				tabela.ajax.reload();
			},

			error: function(xhr, status, error) {
				if(xhr.status == 400) {
					response = xhr.responseJSON.message;
					var conteudo = "";
					for(var i = 0; i < response.length; i++) {
						conteudo += "[" + i + "] - " + response[i] + "<br />";
					}
				}

				generateNoty("topRight", "danger", "Registro não deletado!", conteudo);
			}
		});
	});

	var sortable = $('.posts-sortable').sortable();
	

	$(".btn-salvar-tree").on("click", function() {
		generateNoty("topRight", "info", "Atualizando Ordenação.", "Por favor, aguarde um instante!");

		$.ajax({
			url: "{{ route('admin.posts.editar_ordenacao') }}",
			type: "put",
			data: {"sortable": sortable.sortable("toArray"), '_token': $('input[name=_token]').val()},

			success: function(result, status, xhr) {
				console.log(result);
				generateNoty("topRight", "success", "Ordenação atualizada com Sucesso!", result.message);
				tabela.ajax.reload();
			},

			error: function(xhr, status, error) {
				if(xhr.status == 400) {
					response = xhr.responseJSON.message;
					var conteudo = "";
					for(var i = 0; i < response.length; i++) {
						conteudo += "[" + i + "] - " + response[i] + "<br />";
					}
				}

				generateNoty("topRight", "danger", "Ordenação não feita!", conteudo);
			}
		});
	});
</script>
@endsection